# s = set()
# n = input("Enter number: ")
# s.add((n))
# n = input("Enter number: ")
# s.add((n))
# n = input("Enter number: ")
# s.add((n))
# n = input("Enter number: ")
# s.add((n))
# n = input("Enter number: ")
# s.add((n))
# n = input("Enter number: ")
# s.add(())
# n = input("Enter number: ")
# s.add((n))
# n = input("Enter number: ")
# s.add((n))
# print(s)


s = set()
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
print(s)
